version: "3"
name: akello-dev
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
  cognito-local:
    image: jagregory/cognito-local:latest
    volumes:
      #- ./.cognito:/app/.cognito
      - ${COGNITO_PATH}:/app/.cognito
    ports:
      - "9229:9229"
    environment:
      - CODE=1234
